version: '3.5'
services:
  app:
    image: maven:3-adoptopenjdk-11
    volumes:
      - ./:/app
      - ../maven_cache:/root/.m2
    working_dir: /app
    command:
      - mvn
      - -Dquarkus.http.host=0.0.0.0
      - quarkus:dev
    networks:
      default:
      jnp_applications:
        aliases:
          - users
    expose:
      - 8080
    ports:
      - "8011:8080"

networks:
  jnp_applications:
    name: jnp_applications
    internal: true
