version: '3.5'
services:
  app:
    image: maven:3-adoptopenjdk-11
    volumes:
      - ./:/app
      - ../maven_cache:/root/.m2
    working_dir: /app
    command:
      - mvn
      - -Dquarkus.http.host=0.0.0.0
      - quarkus:dev
    networks:
      default:
      jnp_applications:
        aliases:
          - users
    expose:
      - 8080
    ports:
      - "8011:8080"
    environment:
      - HOST=app1
  appreplica:
    image: maven:3-adoptopenjdk-11
    volumes:
      - ./:/app
      - ../maven_cache:/root/.m2
    working_dir: /app
    command:
      - mvn
      - -Dquarkus.http.host=0.0.0.0
      - quarkus:dev
    networks:
      default:
      jnp_applications:
        aliases:
          - "usersreplica"
    expose:
      - 8080
    ports:
      - "8013:8080"
    environment:
      - HOST=app2
  varnish:
    image: varnish
    volumes:
      - ../varnish:/etc/varnish
    expose:
      - 80
    ports:
      - "8012:80"

networks:
  jnp_applications:
    name: jnp_applications
    internal: true
